#!/bin/bash
#shebang ^

# Define packages to be installed
packages=("kakoune", "tmux")

# Check if user has root privileges if EUID is 0
if [[$EUID - ne 0]]; then 
	echo "This script must be run as root. Please use sudo." >&2
	exit 1
fi


