#!/bin/bash

if [ "$EUID -u" -ne 0 ]; then
    echo "This script must be run as root!" >&2
    exit 1
fi


read -p "Enter username: " username
read -p "Enter absolute path to your shell (basic path it ____: " shell
read -p "Enter additional needed groups (primary default group is "$username": " groups



home_dir="/home/$username"

if [ -d "$home_dir" ]; then
	echo "Directory "$home_dir" already exists!" >&2
	exit 1
else 
	mkdir -p "$home_dir"
	echo "Directory "$home_dir" has been made!"
fi



# copy personal /etc/skel and past it into home_dir
cp -r /home/arch/etc/skel/. "$home_dir"  




cat << EOF >> /etc/group
$username:x:$(($(cut -d: -f3 /etc/passwd | sort -n | tail -n 1) + 1)): $home_dir
EOF
echo "Group "$username" has been added."



cat << EOF >> /etc/passwd
$username:x:$(($(awk -F: '{print $3}' /etc/passwd | sort -n | tail -n 1) + 1)):$(id -g "$username"):$home_dir:$shell
EOF
echo "User "$username" has been added."

